### ISSUE TITLE
XLR interface to #a2council audio

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#102]
Ann Arbor City Council audio is provided on a goofy XLR interface port that is so obscure that even the Ann Arbor Kiwanis sale's box of "miscellaneous cables" does not have an adapter for.

**Comment by cdzombak** [comment]
Do you have a photo?

What sort of cable are you looking for—ie. what are you trying to connect it to?

**Comment by vielmetti** [comment]
Chris, this is for City Hall, specifically the room where Ann Arbor City Council meets. There are audio output (or maybe input?) jacks in the back, and I'm pretty sure they are fed by the sound board. I'd like to plug into them and pull that audio and transmit it to the net (probably through Youtube or UStream or ... you name it, something). The pinout is XLR but we don't know much more than that.

**Comment by larryworks** [comment]
Ed,

My son has a basic sound system that does this. He knows how to use it for
music production. Same principles apply for what you want to do.

Soundboards vary. Basically you'll have microphones recording (XLR jack)
with 1 source/input channel). The soundboard combines input channels to
create audio XLR output(s).

If it's live performance, that audio goes to an amplifer then to speakers.

Alternatively, the output can go through a mixer.   Many digital mixers
handle both analog and digital inputs. The mixer uses hardware and sofware
to combine inputs and create a digital output for recording.  To whatever
file format you choose.

Without seeing the hardware at City Hall, can't say much more.  Know folks
who can though.  John Hritz is probably one of them and there are several
who attend Go-Tech at MakerWorks.

Hope this helps.
Larry

Chris, this is for City Hall, specifically the room where Ann Arbor City
Council meets. There are audio output (or maybe input?) jacks in the back,
and I'm pretty sure they are fed by the sound board. I'd like to plug into
them and pull that audio and transmit it to the net (probably through
Youtube or UStream or ... you name it, something). The pinout is XLR but we
don't know much more than that.

—
Reply to this email directly or view it on GitHub
<https://github.com/a2civictech/a2civictech/issues/102#issuecomment-96309754>
.

**Comment by vielmetti** [comment]
AHA, this starts to make more sense.

http://www.monoprice.com/Product?p_id=615808 from Monoprice is an $85 mixer that looks like it would accomplish the task at hand (to start with audio from City Hall and produce audio that I could get into my Macbook Air).

Given that I wonder if AADL's music tools set has a tool that is a mixer with perhaps even proper cables.

**Comment by vielmetti** [comment]
Cable, if I'm looking for a cable, might be this one:

![screen shot 2015-04-26 at 7 01 57 am](https://cloud.githubusercontent.com/assets/35047/7336938/3b033d8e-ebe2-11e4-811b-277c5bdeb0d4.png)

**Comment by vielmetti** [comment]
Note also that there's an audio jack at the right of the podium that may provide an easier place to patch into the sound system.
