### ISSUE TITLE
Contact Jeff Irwin to present on FOIA changes

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#112]
FOIA laws are changing, an upcoming a2civictech event should discuss the changes. Talk to Jeff Irwin

**Comment by vielmetti** [comment]
"I appreciate the invitation and I'd like to do it given that we can find the right Monday. "

**Comment by cdzombak** [comment]
This should be really interesting.

**Comment by vielmetti** [comment]
Yup @cdzombak this should be good. I've also reached out to @superscot (Saline superintendent) who went through some kind of FOIA training, and there might be materials also available from the Michigan Municipal League.

**Comment by vielmetti** [comment]
The cookies sponsor has been lined up (Fred Posner, Dream Day Cakes).

**Comment by vielmetti** [comment]
Email from @superscot says he's looking forward to attending.
