### ISSUE TITLE
Tran Longmoore / Saline Post / Washtenaw County Sheriff FOIA charges

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#130]
The Twitter string is here:

https://twitter.com/TranLongmoore/status/593900546781814786

```
@WashtenawCounty @WSheriff charges $86 to print off a 
police report. Nice. That seem about right to you @vielmetti?
```

Inquire to Washtenaw County as to whether the fees were calculated according to policy, Judy Kramer is point of contact.

**Comment by TranLongmoore** [comment]
Labor: 2.4 hours at $31.87/hour. The only work beyond hitting print, as far as I can tell, was redacting personal information of names in a police report.
This is my beef. Especially considering this same report was likely accessed by City of Saline government, a local lawyer.

**Comment by vielmetti** [comment]
@TranLongmoore I sent in a FOIA to Washtenaw County on Friday 5/15 for a copy of your FOIA plus any processing notes or correspondence relating to the request. 

Judy Kramer from Washtenaw Co writes:

> I know this one as I handled the request myself.  He was charged appropriately, but if you have questions please let me know

the FOIA is aimed at getting to this.

**Comment by vielmetti** [comment]
FOIA response for the processing log for this record reviewed. The 2.4 hr time spent is backed up by handwritten notes on paper showing dates and times that the request was worked on. The request itself included 50+ pages of police report transcript and there was time allocated to redacting that line by line.
