### ISSUE TITLE
arrange new home for a2docs

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#14]
We have a working agreement to put it at AADL; when the time comes, make it so.

- [ ] #97 Resolve issues with Scribd for hosting so that a2docs can get uploads again
- [x] #20 get a tarball of the database
- [ ] document the structure of the tarball
- [x] convey tarball to AADL
- [x] AADL unpacks and puts into nodes and other long term storage.

**Comment by vielmetti** [comment]
Asked Brian Kerr for a tarball.

**Comment by vielmetti** [comment]
https://bitbucket.org/bkerr/ann-arbor-government-documents/ is the source tree.

**Comment by cdzombak** [comment]
> https://bitbucket.org/bkerr/ann-arbor-government-documents/ is the source tree.

Just got back into town; I'll take a look when I have a chance!

**Comment by vielmetti** [comment]
tarballs acquired. It's about a gigabyte of source materials, but not that much code.

**Comment by vielmetti** [comment]
A status: with @cdzombak 's help, I uploaded the a2docs source code to https://github.com/a2civictech/a2docs-sources . the 'master' branch now also has a working .travis.yml file that invokes Travis, and it successfully installs a batch of dependencies with 'pip'. 

I don't know yet if I have all of the dependencies, and I don't have any tests, but *something* does work, and that's kind of a first step.

**Comment by vielmetti** [comment]
Seeking experienced Django skills at a negotiated rate to take this on or at least to provide an estimate so that fundraising can begin.

**Comment by vielmetti** [comment]
Thanks to @steiza and @eby we have this working at AADL. Closing.
