### ISSUE TITLE
Sidewalk hole in front of Colonial Lanes

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#146]
![sidewalk-hole](https://cloud.githubusercontent.com/assets/35047/7937814/17ed1ae0-0910-11e5-8ab5-6a667a3c256b.jpg)

Reported at http://seeclickfix.com/issues/1683475-sidewalk-issue

**Comment by cdzombak** [comment]
The bigger issue here is that there are utility poles in the middle of the sidewalk, but I don't suppose SeeClickFix can fix that. :(

**Comment by vielmetti** [comment]
Said to have been fixed temporarily with cold patch. I spoke with an Adam Ajam, Civil Engineering Specialist, (734) 323-5656.

**Comment by vielmetti** [comment]
Hole is filled, closing.
