### ISSUE TITLE
Arborwiki: Set down policies for "people who don't want to be included" who are public figures

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#151]
Sort out how to deal with public people who don't want to be written up on Arborwiki 

Refer to https://localwiki.org/ann-arbor/Patricia_Lesko/_history/ for a case study.

**Comment by cdzombak** [comment]
> Sort out how to deal with public people who don't want to be written up on Arborwiki

If you've written op-eds, run for local political office, and otherwise made yourself into a public figure, you don't get to choose who documents facts about your public life.
