### ISSUE TITLE
Legistar: PDFs cannot be downloaded

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#189]
Reported here: https://seeclickfix.com/issues/2676761-legistar-cant-download-pdfs based on report by Scott Trudeau.

PDF attachments to the Legistar are not downloading. Repeat by:

http://a2gov.legistar.com/LegislationDetail.aspx?ID=2778331&GUID=9B9994C7-E2C3-4B50-BF81-4F98863F5D8F

download . "Woodbury Club Staff Report with Attachments-7-12-16.pdf" you get a blank page.

**Comment by cdzombak** [comment]
confirmed broken for me on Safari Version 9.1.1; OS X 10.11.5.

**Comment by cdzombak** [comment]
To be clear, I tested only the linked test case. Dave has pointed out on Twitter another PDF link that works fine.

**Comment by cdzombak** [comment]
That tweet: https://twitter.com/chronicallydave/status/751898298332553216

**Comment by vielmetti** [comment]
Problem fixed, closing this issue.
