### ISSUE TITLE
MRF FOIAs: 448, 447, 419, 398

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#191]
Please refer to this paragraph in FOIA request 398, in a letter to Mike Brennan of ReCommunity:

"The City invokes its right to terminate under Section 12.02(c) based on continuing unsafe operations by ReCommunity. By the City’s letter dated June 10, 2016, you were put on notice that the City reserved its right to terminate if safety deficiencies continued. Both City safety personnel and the City’s contracted safety inspectors have observed and documented that safety deficiencies have continued without break since June 10, 2016. All of these reports have been shared with ReCommunity personnel on site and with Linda Fendrick-Crowther."

Please provide the following records under FOIA:
1. The City’s letter dated June 10, 2016 to ReCommunity, as mentioned above; and
2. The above mentioned safety reports on the MRF, as "shared with ReCommunity personnel on site and with Linda Fendrick-Crowther". 

I don't think there will be any costs associated with this request; please contact me first before proceeding if there will be any fees.

Thank you.

Edward Vielmetti

Received 7/19/2016  
Due 7/26/2016

**Comment by vielmetti** [comment]
A portion of the MRF FOIA came back, and I put the documents on a2docs

http://a2docs.org/view/424

Lots of photos of unappealing working conditions, and some obvious safety issues like emergency exits completely blocked with trash.

![screen shot 2016-07-26 at 4 43 47 pm](https://cloud.githubusercontent.com/assets/35047/17160632/69d7eccc-5374-11e6-9248-793de9e7ed4d.png)

I didn't get a denial, but I also didn't get everything I asked for, so I'm clarifying that with the clerk right now.

**Comment by vielmetti** [comment]
The remainder of the documents came back, process those next. They refer to additional previous documents which will be the subject of the next FOIA.

**Comment by cdzombak** [comment]
thanks for tracking this, @vielmetti

**Comment by vielmetti** [comment]
Thanks @cdzombak . The next document dump should be even larger, if my instincts are right.

**Comment by vielmetti** [comment]
Now up, http://a2docs.org/view/425 - which is the letter from the City to ReCommunity informing them of safety issues.

On June 10, 2016, the City of Ann Arbor sent this "Notice of Defaul and of Opportunity to Cure " to ReCommunity regarding safety deficiencies at the Ann Arbor Materials Recovery Facility (MRF). It spells out the safety issues at the MRF plant. Quoting:

"ReCommunity has repeatedly been given notice of and required to correct numerous, serious safety violations and/or deficiencies (violations and deficiencies may be referred to herein collectively or alternatively as “deficiencies”) at the MRF, as well as at the TS. Other safety deficiencies have been noted in fire inspection reports. "

--

This document references previous files and inspection reports, which will be the subject of a future FOIA.

**Comment by cdzombak** [comment]
I'm curious to see the history of inspection reports and fire inspection reports, going back a few years. How often were inspections conducted historically? Did we really start frequent inspections only in June of this year as implied by the documents in http://a2docs.org/view/424 ? Why?

**Comment by cdzombak** [comment]
> This document references previous files and inspection reports, which will be the subject of a future FOIA.

I am very curious to see those reports.

**Comment by vielmetti** [comment]
New FOIA submitted,

Thank you for submitting a FOIA Request. Your FOIA ID is 447.

I've updated the header for this request to track it

**Comment by vielmetti** [comment]
This is what was requested in 447:

--

Please refer to the following paragraph, as found in FOIA request 419:

"As set out in prior emails, in conversations with ReCommunity personnel, and in the reports prepared and provided to ReCommunity after the City’s monthly (and now more frequent) inspections of the MRF, ReCommunity has repeatedly been given notice of and required to correct numerous, serious safety violations and/or deficiencies (violations and deficiencies may be referred to herein collectively or alternatively as “deficiencies”) at the MRF, as well as at the TS. Other safety deficiencies have been noted in fire inspection reports. These safety deficiencies have persisted and/or recurred on a regular basis despite the repeated notices and opportunities to correct them. A recent report described the findings of the May 31, 2016, inspection. Just after that report, ReCommunity experienced another fire at the MRF. The City believes the fire could have been prevented through proper maintenance of equipment, and proper attention to and awareness of operations, and that the failures to do so resulted in the fire and created a serious threat to safety."

Please provide the following records:

1. Records of monthly inspection reports of the MRF, beginning in January 2016 and continuing through the May 31, 2016 inspection noted above;
2. Records of the "The safety inspections done on June 4, 6 and 7, 2016" of the MRF
3. Records of "fire inspection reports" as mentioned in the above paragraph for the MRF, for calendar year 2016;
4. Any "Fire Department Incident Records" for fires in calendar year 2016 at the MRF; specifically for a fire of unknown date in early June 2016 referenced in that paragraph.

Thank you for your prompt attention to this request. I do not anticipate any fees for this request.

Thanks again

Ed

**Comment by vielmetti** [comment]
I've added also the copy of the Federal lawsuit against the city, as provided by the Ann Arbor News, here

http://a2docs.org/view/426

**Comment by cdzombak** [comment]
In the suit, ReCommunity claims,

>  30. ReCommunity has made several efforts to work with the City to
amend the Contract and address the City’s financial concerns, sending the City multiple proposals to amend the Contract.
> 31. Ann Arbor has failed to respond to these submissions. Instead, the City engaged a consultant to help it find a way to avoid its obligations to ReCommunity under the Contract.

Those proposals and any responses to them might be interesting to FOIA … but then, they'll probably come out in court, so it may not be worth the effort.

**Comment by cdzombak** [comment]
Other items mentioned in the suit:

> 43 The City’s concerns were refuted by an independent review, which found that the Plant’s equipment was overall in good operating condition.
> 
> 45 On April 21, 2016, owing nearly a quarter million dollars of Net Negative Amounts, the City sent ReCommunity a letter citing an alleged breach of Section 4.01 of the Contract based on the fact that ReCommunity sourced materials from certain third parties. Ann Arbor wrongly claimed that it had not approved of these third-party agreements, the tonnages were beyond the Plant’s capacity, and the materials were causing safety violations and concerns.

The result of that independent review and that April 21 letter might also be interesting.

**Comment by cdzombak** [comment]
Oh man.

> 55 On June 13, 2016, ReCommunity sent Ann Arbor a letter informing the City of an Event of Default by the City pursuant to Section 12.03 of the Contract.
>
>56 In particular, ReCommunity identified the City’s “persistent and repeated failure” to pay the amounts due under the revenue sharing portion of the Contract.
>
>57 ReCommunity informed Ann Arbor that its continued failure to correct the default within 30days would force ReCommunity to seek an appropriate remedy.
>
>58 On June 28, 2016, Ann Arbor responded to ReCommunity’s June 13, 2016 letter, denying that it was in default for failure to pay.

Now _that_ should be interesting correspondence to review. @vielmetti, let me know if you want me to handle requesting any of these documents.

**Comment by cdzombak** [comment]
The City/ReCommunity contract itself would be interesting to review.

**Comment by vielmetti** [comment]
Here's the contract, @cdzombak - 

http://a2docs.org/view/427

![screen shot 2016-07-28 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/35047/17226732/cf6711b6-54d8-11e6-9140-d374347fa69a.png)

**Comment by vielmetti** [comment]
Chris, if you could make another FOIA for the documents you identified that would be great.

**Comment by cdzombak** [comment]
Submitted the following FOIA #448 in an attempt to find the documents I mentioned above while reading the lawsuit.

Response is due Thursday, August 4.

---

I am writing to request correspondence and documents mentioned in the lawsuit filed against the City by Resource Recovery Systems on July 27, 2016 in the US District Court of Eastern Michigan, Southern Division. My specific requests follow, with context.

The lawsuit claims, "23. In addition, as Ann Arbor officials acknowledged in October 2014, Ann Arbor promised to be responsible for all of ReCommunity’s costs attributable to the transport of third-party materials to the Plant."

Please provide copies of correspondence between the City and ReCommunity dated in October of 2014.

The lawsuit claims, "26. ReCommunity obtained third-party contracts, notified the City in writing on a monthly basis of such third-party arrangements, processed materials pursuant to those contracts, …"

Please provide documents reflecting any such notifications from ReCommunity, from calendar years 2013 through 2016.

The lawsuit claims, "30. ReCommunity has made several efforts to work with the City to
amend the Contract and address the City’s financial concerns, sending the City multiple proposals to amend the Contract."

Please provide copies of any such proposals from ReCommunity, from calendar years 2011 through 2016, and the City's responses, if any, to these proposals.

On January 19, 2016, City Council awarded a contract to CB&I Environmental & Infrastructure, Inc. for Material Recycling Facility Contract Development and Contingency. (This was the result of RFP No. 931 and enactment # R-16-022.)

Please provide copies of City documents providing direction to that firm or its consultants, and any documents or reports resulting from this firm's work under this contract.

The lawsuit claims, "43. The City’s concerns were refuted by an independent review, which found that the Plant’s equipment was overall in good operating condition."

Please provide any documentation the City possesses resulting from such independent reviews of operations at the MRF, from calendar years 2013 through 2016.

The lawsuit claims, "45. On April 21, 2016, owing nearly a quarter million dollars of Net Negative Amounts, the City sent ReCommunity a letter citing an alleged breach of Section 4.01 of the Contract based on the fact that ReCommunity sourced materials from certain third parties."

Please provide a copy of that letter and any subsequent, related correspondence between ReCommunity and the City.

The lawsuit claims, "55. On June 13, 2016, ReCommunity sent Ann Arbor a letter informing the City of an Event of Default by the City pursuant to Section 12.03 of the Contract." and "58. On June 28, 2016, Ann Arbor responded to ReCommunity’s June 13, 2016 letter, denying that it was in default for failure to pay."

Please provide a copy of those two letters and any subsequent, related correspondence between ReCommunity and the City.

I do not anticipate any significant fees to be associated with this request. If there are costs above $20 for searching or copying these records, please contact me before proceeding.

Thank you for your attention to this request.

**Comment by vielmetti** [comment]
FOIA 447 has come back, with many megabytes of records. Details here

http://a2docs.org/view/429

In particular, there are 6 months worth of inspection reports with photos, and three separate fire inspection reports showing extended periods of non-compliance with fire dep't safety requirements.

**Comment by vielmetti** [comment]
@cdzombak : we should be getting back your FOIA 448 soon too.

**Comment by cdzombak** [comment]
> we should be getting back your FOIA 448 soon too.

Good point. I'm out of town right now, so if a response arrived via mail I won't see it for a couple more days. I haven't seen a response, or an extension, via email (unless I missed it, which is unlikely).

**Comment by cdzombak** [comment]
I see nothing in my spam inbox, so it would seem my request is overdue.

**Comment by vielmetti** [comment]
Looks like they are asking for a deposit, per the database on 

https://www.a2gov.org/departments/city-clerk/pages/foia-requests.aspx

**Comment by cdzombak** [comment]
> Looks like they are asking for a deposit, …

I haven't heard anything via email. Will look for something in my USPS mail and check in with the City if I see nothing.

**Comment by cdzombak** [comment]
I emailed the clerk this morning, after double checking I have received no correspondence re: FOIA 448.

**Comment by cdzombak** [comment]
I got the following response for FOIA 448, which they say was emailed on August 2: https://dropbox.dzombak.com/civtech/Deposit%20%26%20Extension%20Ltr-448%20Dzombak.pdf

Notably, it includes an estimated bill of $96.

@vielmetti: my plan is to email back and see why this estimation is so high, to see if I can change the request to be significantly cheaper while still providing useful information.

**Comment by vielmetti** [comment]
Sounds like a good plan, Chris - I'm betting there's one thing you're asking for that triggers the 3 hr search, and the rest will be gratis.

**Comment by vielmetti** [comment]
The Recommunity PR re the lawsuit is here, from July:

http://www.prnewswire.com/news-releases/recommunity-files-federal-lawsuit-against-city-of-ann-arbor-300305701.html

I've emailed the PR contact to ask if they have any updates.

**Comment by cdzombak** [comment]
I asked for a revised estimate on the FOIA I mentioned in https://github.com/a2civictech/a2civictech/issues/191#issuecomment-240832712 a while back, and received no response. I don't feel too strongly about pursing this one further.

**Comment by vielmetti** [comment]
Closing
