### ISSUE TITLE
Move Wiki content into a2civictech repo

### ISSUE THREAD

**Issue by cdzombak** [a2civictech/a2civictech#193]
As outlined in [my blog post on this subject](https://www.dzombak.com/blog/2015/03/Why-use-GitHub-Wikis-.html), I would advocate for moving [our Wiki content](https://github.com/a2civictech/a2civictech/wiki) into this repository directly.

There is currently [one wiki page](https://github.com/a2civictech/a2civictech/wiki/October-2014-Meetup-notes) which could be moved to [this apparent placeholder Markdown file in the repo](https://github.com/a2civictech/a2civictech/blob/master/a2civictech/2014-10-27-minutes.md).

@vielmetti if you approve, reassign this to me and I'll take care of it. Otherwise go ahead and close as `wontfix`.

**Comment by vielmetti** [comment]
Go for it Chris!

**Comment by vielmetti** [comment]
And when you're done emptying the wiki, we can disable it too.

**Comment by cdzombak** [comment]
Those minutes have been moved & the wiki disabled. Thanks, @vielmetti
