### ISSUE TITLE
AAATA API [FOIA due August 26 2016]

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#195]
The AAATA is working on an API for transit data, track efforts to use that data here.

**Comment by vielmetti** [comment]
AAATA has a public meeting tonight which would be an appropriate venue for a query (630p, AADL 4th floor downtown).

I've seen that they have at least part of some API in internal use for driving the signs at the Central Campus Transit Center, signs that had been inactive for a long time.

**Comment by vielmetti** [comment]
I wonder whether a FOIA request would speed this process up or slow it down. The query I have in mind is for "all email to developers@theride.org, and all responses to those messages", for this calendar year.

**Comment by cdzombak** [comment]
> all email to developers@theride.org, and all responses to those messages

**Comment by vielmetti** [comment]
FOIA sent, to dgabay@theride.org.

```
This is a request under the Michigan Freedom of Information Act.  

Please provide the following records:

1. All email to developers@theride.org in calendar year 2016
2. All responses to those messages in (1)

Thank you for your prompt response to this query. I do not anticipate
any charge for this request; please inform me before proceeding if
there will be any charges.

Please provide the records in electronic format via email to
edward.vielmetti@gmail.com . 
```

**Comment by vielmetti** [comment]
Expecting a response by August 26.

**Comment by vielmetti** [comment]
Dawn Gabay is the AAATA FOIA coordinator, and is out of the office until 8/23. Her away message directs me at Karen Wheeler, and I've forwarded the FOIA accordingly.

**Comment by vielmetti** [comment]
From AAATA:

On behalf of Ms. Gabay, the estimated amount to compile the requested information is $87.96.  A 50% deposit is required ($43.98).  Please let us know how you wish to proceed.

**Comment by vielmetti** [comment]
I decided not to pursue this FOIA, closing.
