### ISSUE TITLE
Handwritten minutes of City of Ann Arbor public meetings [FOIA 471]

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#196]
Noted at Ann Arbor City Council tonight; in the Legistar packet there are handwritten meeting minutes that resist easy reading (let alone scanning of documents for keyword, or accessible reading via a screen reader).

![image](https://cloud.githubusercontent.com/assets/35047/17687100/16994d40-6340-11e6-8d2d-99bdb7d63bc3.png)

I've asked the clerk to provide readable versions of these minutes, which are from the Ann Arbor City Council Administration Committee.

**Comment by vielmetti** [comment]
Awaiting a reply from the clerk; I've informed members of the Disability Commission, since it's an access issue.

**Comment by vielmetti** [comment]
Got support via email from several members of the Disability Commission, but nothing yet back from the clerk.

**Comment by vielmetti** [comment]
Copy of letter to clerk also sent to City Attorney.

**Comment by vielmetti** [comment]
3 days later nothing from the clerk, so I'm going to file this as a FOIA too so that it gets tracked.

**Comment by vielmetti** [comment]
FOIA 471 filed.

**Comment by vielmetti** [comment]
Spoke with Carolyn Grawi (Ann Arbor Center for Independent Living) who added her support to the effort.

**Comment by vielmetti** [comment]
FOIA was rejected (records do not exist), but this hopeful note from the clerk:

> Attached is the City’s response to your FOIA request for machine-readable minutes of the Council Administration committee. As you have requested records that do not exist, your FOIA request is denied. With respect to Council Administration minutes, please note that future minutes will be submitted for filing in a typed format, rather than handwritten.

**Comment by cdzombak** [comment]
That's promising!

**Comment by vielmetti** [comment]
Update: The latest minutes were typed, but the copy filed with the clerk was provided on paper. The clerk then scanned in the minutes, in a format that was legible (compared to handwriting) but still not searchable in Legistar and still not accurately OCR'able using Tesseract. 

I spoke with the clerk at the 9/5 council meeting and she indicated that she'd obtain fully electronic minutes for future meetings.

**Comment by vielmetti** [comment]
Recategorized as "meeting minutes", and closing as complete.
