### ISSUE TITLE
Minutes of Executive Committee of City Planning Commission [FOIA 469]

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#197]
I requested the minutes of the August 12, 2016 City Planning Commission Executive Committee, an unusual committee in that it meets by telephone, and also unusual in that it has not in the past produced meeting minutes (or even much in the way of announcements of meetings).

"Thank you for submitting a FOIA Request. Your FOIA ID is 469."

**Comment by vielmetti** [comment]
Expect a response by August 25 or so.

**Comment by vielmetti** [comment]
Response date is 8/24

**Comment by vielmetti** [comment]
Response was denial, as the records do not exist (i.e. they are not keeping minutes of this committee meeting).

I think the only reasonable thing to do is to appeal, and also to go to the next meeting, once I figure out what date/time that meeting is.

**Comment by cdzombak** [comment]
What will a FOIA appeal solve, if the committee isn't keeping minutes? I'd imagine the appropriate response is escalating the lack-of-minutes issue somehow; is a FOIA appeal the right way?

**Comment by vielmetti** [comment]
Yeah, I think the thing to do is to attend the meeting, and talk to people before or after to see if there could be minutes kept or even a record of who is there. I'll also bring this up with the people who are on that committee to see what they say.

**Comment by vielmetti** [comment]
No meetings of the Executive Committee are currently scheduled for 2016, and there are no scheduled meetings for any of the Planning Commission for 2017 (dates not set yet).
