### ISSUE TITLE
Light post at northeast corner of Huron/Main

### ISSUE THREAD

**Issue by cdzombak** [a2civictech/a2civictech#200]
Now that the M-14 construction is done, we should try to get the damaged lightpost at this intersection fixed or replaced.

I'll submit a fix-it request next time I walk past, but is this the city's job or MDOT's?

**Comment by cdzombak** [comment]
If it doesn't get resolved in the short term, _someone_ could buy some glossy black paint and fix it themselves, too…

**Comment by vielmetti** [comment]
What's the problem with the post, is it structural or paint or both?

**Comment by cdzombak** [comment]
It's heavily dented (but probably still structurally sound), and the paint is scraped off, from trucks hitting it while turning right from southbound Main to westbound Huron.

**Comment by vielmetti** [comment]
Reported to SeeClickFix / A2 Fix It at https://seeclickfix.com/issues/2829815-light-post-dented-and-scraped

**Comment by cdzombak** [comment]
thanks, Ed.

**Comment by cdzombak** [comment]
> DTE pole. Sent request for repair to DTE 08/25/2016

I wonder how long _that_ will take :/
