### ISSUE TITLE
Pontiac Trail construction

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#202]
Pontiac Trail is under construction, and signage appears to be bad. Track this to resolution (before someone gets injured going wrong way down a one way street).

Open tickets:
- [ ] [Barton and Starwick](https://seeclickfix.com/issues/2891753-need-sign-road-closed-at-pontiac-trl)
- [ ] [Pear Street](https://seeclickfix.com/issues/2883140-dangerous-construction)
- [ ] [Chandler Street](https://seeclickfix.com/issues/2881567-traffic-during-pontiac-tr-construction)
- [ ] [Barton Drive](https://seeclickfix.com/issues/2884103-traffic-issues)
- [x] [Wrong way traffic on Pontiac Trail](https://seeclickfix.com/issues/2892829-inadequate-signage-for-road-closure)

**Comment by vielmetti** [comment]
I gave public comment at the Monday Council working session. Mr Hupy assured me that a bunch changes were underway to traffic control and would be in place Tuesday, and he said that members of council had been updated to the situation.

**Comment by vielmetti** [comment]
Pontiac trail road closed signs added "Do Not Enter" signs. Photo Philip Proefrock.

https://twitter.com/cornellbox/status/778045169568481280

![image](https://cloud.githubusercontent.com/assets/35047/18656914/4dae8b26-7ec3-11e6-9cbd-2ed0738c1775.png)

**Comment by vielmetti** [comment]
Mission accomplished.

**Comment by cdzombak** [comment]
well done — without those signs I could easily imagine some poor, confused driver going the wrong way, with predictable results.
