### ISSUE TITLE
a2docs.aadl.org cert error

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#206]
![screen shot 2016-09-13 at 5 31 57 pm](https://cloud.githubusercontent.com/assets/35047/18492212/0c712bea-79d8-11e6-8b60-2f0c8bda47c0.png)

From Chrome:

Your connection is not private

Attackers might be trying to steal your information from a2docs.aadl.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID
  Automatically report details of possible security incidents to Google. Privacy policy

a2docs.aadl.org normally uses encryption to protect your information. When Google Chrome tried to connect to a2docs.aadl.org this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be a2docs.aadl.org, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit a2docs.aadl.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by vielmetti** [comment]
Note that http://a2docs.org works just fine.

**Comment by eby** [comment]
Updated the SSL certificate to our latest wildcard. Redirect to the normal domain should work as expected now.

**Comment by vielmetti** [comment]
Confirmed working, thanks!
