### ISSUE TITLE
City of Ann Arbor - Geddes sewer overflow

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#211]
From the city:

http://www.a2gov.org/news/pages/article.aspx?i=308

At approximately 7 a.m. on Monday, Sept. 19, 2016, a sanitary sewer overflow was discovered in the construction area on Geddes Road near the entrance to Gallup Park. The cause of the overflow was determined to be construction debris that had accumulated in a sanitary sewer pipe, blocking flow. The blockage was immediately removed and flow restored. The overflow occurred sometime between 3 p.m. on Saturday, Sept. 17, 2016, and Monday, Sept. 19, 2016, at 7 a.m. It is estimated that up to 600,000 gallons of sewage reached the Huron River.

There are no communities downstream of the plant that withdraws water from the Huron River for drinking purposes. In accordance with regulatory protocols, City of Ann Arbor staff contacted the Michigan Department of Environmental Quality to inform them of this unfortunate incident. The Gallup Park canoe livery has suspended Geddes Pond stillwater paddles and the Argo-Gallup canoe trips until water test results are obtained.

---

600000 gallons of sewage!!!!

Not sure what the action item is here, but it might include some kind of request for more information.

**Comment by cdzombak** [comment]
> Not sure what the action item is here, but it might include some kind of request for more information.

possible questions, but not sure this is worth anyone's time to pursue (I don't know what we'd be trying to accomplish):
- what construction company[ies] is working here?
- what communications if any did the city send the company as a result?
- are there any penalties as a result?

**Comment by vielmetti** [comment]
MLive has some of those answers here: http://www.mlive.com/news/ann-arbor/index.ssf/2016/09/city_administrator_on_sewage_s.html

> The City Council voted last year to award a $6.9 million contract to Midland-based Tri-City Groundbreakers Inc. for the Geddes Avenue road reconstruction project. The work is ongoing.
> 
> John Schmidt of Tri-City Groundbreakers said Tuesday morning he was headed to the site and would provide comment later in the day after he had more information following a project meeting. He declined to comment until then.

**Comment by vielmetti** [comment]
More MLive quoting Kellar

http://www.mlive.com/news/ann-arbor/index.ssf/2016/09/massive_sewage_spill_on_huron.html

> Lazarus said the city has received a photograph from a resident showing a car driving on the road and the city is looking into it.
> 
> Robert Kellar, a spokesman for the city, said he had no new information to share, but city staff is working on a complete event summary that will be provided to the City Council and made public. He said it's hoped it will be completed today.

When I talked to Kellar this a.m. he did not share any information beyond this except to use the word "stupid" and to tell a story of a different incident where someone drove onto fresh hot asphalt and spun their tires. He was preparing to share with City Council first before the press.

**Comment by vielmetti** [comment]
http://arborwiki.org/September_2016_sewage_spill (in progress)

**Comment by vielmetti** [comment]
[Skyline crew team didn't know of sewage overflow before Monday practice](http://www.mlive.com/news/ann-arbor/index.ssf/2016/09/skyline_crew_team_was_not_noti.html#incart_river_index)

> A sanitary sewer overflow was discovered in a construction area on Geddes Avenue near the entrance to Gallup Park at about 7 a.m. Monday, Sept 19. The City of Ann Arbor issued a press release about the incident at about 5 p.m. Monday, after the team of Skyline students already was on the river.

**Comment by vielmetti** [comment]
A portion of a press release sent by email today:

> In response to the event, city staff acted as quickly as possible with the information available and met all regulatory reporting requirements. After a review of events, the city has identified improvements to be implemented, both at construction sites and in communications practices, should future sanitary sewer overflow events occur. These improvements are to include enhanced internal training regarding construction site release protocols as well as expanded notifications. Additional notifications are not required by MDEQ and may lack the detail available in later releases, but in doing so, the city would aim to give the community peace of mind that everything possible is being done to keep the public informed.

**Comment by vielmetti** [comment]
Yet another sewage spill at Geddes, though not a big one and not related to the other.

> At approximately 11 a.m. on Friday, Sept. 23, 2016, a sanitary sewer overflow occurred in the construction area on Geddes Avenue near the entrance to Gallup Park. The overflow resulted when a hose broke during bypass pumping operations for a sanitary sewer pipe rehabilitation project. The pumps were immediately shut down. All sewage was contained on land in the area immediately adjacent to the overflow. There were no impacts to storm water or the Huron River. This overflow is in no way related to the overflow earlier in the week and is part of a different project and different contractor.
> 
> It is estimated that 200 gallons of sewage was released. The impacted area was cleaned and treated with a powdered lime to neutralize and accelerate the decomposition of any remaining sewage. As a precaution, the impacted area has been cordoned off with tape. Pedestrians in the area are advised to stay on the designated path.
> 
> In accordance with regulatory protocols, City of Ann Arbor staff contacted the Michigan Department of Environmental Quality to inform them of this unfortunate incident.
