### ISSUE TITLE
fixing a2docs typoes

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#219]
Two errors in http://a2docs.org/view/445 - I don't have access to an admin interface for fixing edits that are not quite right.

So, it should be ...

"dates back to 1988 and is being reopened."
"Connors on Dec. 15, 2016, agreed to grant all three motions"

**Comment by vielmetti** [comment]
attn @a2civictech/a2docs-team

**Comment by eby** [comment]
should be updated and I'll dm you the info so you can fix going forward

**Comment by vielmetti** [comment]
thanks @eby !
