### ISSUE TITLE
a2docs - let's encrypt NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#230]
a2docs is showing a NET::ERR_CERT_DATE_INVALID error, perhaps because Let's Encrypt did not renew?

**Comment by vielmetti** [comment]
When something similar last happened #206 it was @eby to the rescue

**Comment by eby** [comment]
fixed. it renewed but i've noticed that reload doesnt always refresh certs randomly. i've moved to doing a restart but missed updating the hook here

**Comment by vielmetti** [comment]
@eby you are the best! thanks
