### ISSUE TITLE
Report on closed captioning by CTN of Ann Arbor City Council meetings

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#62]
Lisa W is probably the contact at a2gov

**Comment by vielmetti** [comment]
As I understand it, CTN is closed captioning disability commission meetings, and is considering same for City Council. I don't know the cost, but that should be answerable.

**Comment by vielmetti** [comment]
Asked Lisa Wondrash for info.

**Comment by vielmetti** [comment]
Thank you for submitting a FOIA Request. Your FOIA ID is 470.

Asked for minutes of the Cable Communications Commission, which has met two or three times in 2016 but has not produced minutes, and which has considered this topic.

**Comment by vielmetti** [comment]
Closed captioning is on the council agenda for tonight. Suggest that a2gov spend the money to caption council meetings.

**Comment by vielmetti** [comment]
The closed captioning ordinance, which would require businesses to turn CC on in public, was tabled to 1st week of Feb based on problems with the wording. Public comment focused on the city's own budget to closed caption its own meetings.

**Comment by cdzombak** [comment]
> Public comment focused on the city's own budget to closed caption its own meetings.

Thanks, Ed :)

**Comment by vielmetti** [comment]
Closed captioning is "on" for City Council meetings, consider this a success. Closing.
