### ISSUE TITLE
Set up multiple people with access to a2civictech tumblr

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#91]
Recruit and teach people how to contribute to the a2civictech tumblr, 

http://a2civictech.tumblr.com

**Comment by vielmetti** [comment]
The tumblr has two entries, which isn't really a sign of life.

**Comment by cdzombak** [comment]
> The tumblr has two entries, which isn't really a sign of life.

What is the intended use for this tumblr?

**Comment by vielmetti** [comment]
It was once upon a time thought to be a good idea maybe for a group blog. I'd be inclined to kill it now, as surplus and attention-diverting.

**Comment by vielmetti** [comment]
I've deleted this tumblr.
