### ISSUE TITLE
set up email address as an exploder to contact a2civictech leadership

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#93]
- [x] Set up a2civictech@umich.edu as an email address to go to multiple leaders of group.
- [ ] Ask others to get copies of this mail.
- [ ] Promote address as a point of contact

**Comment by vielmetti** [comment]
Not the right approach, but also not a topic of current interest, so close.

**Comment by cdzombak** [comment]
we should likely promote a2civtech-slack.herokuapp.com instead

**Comment by vielmetti** [comment]
Great idea @cdzombak - I posted something to Twitter to that effect just now.

**Comment by vielmetti** [comment]
Replaced by #186
